Hopefully fix build failure on Travis CI
$ clang --version
clang version 5.0.0 (tags/RELEASE_500/final)

$ qmake -spec linux-clang && make check
[...]
clang++ -c -pipe -Werror -Wextra -pedantic -O2 -std=c++11 -Wall -W
-D_REENTRANT -fPIE -DQT_NO_CAST_FROM_ASCII -DQT_NO_CAST_TO_ASCII
-DQT_NO_DEBUG -DQT_TESTLIB_LIB -DQT_GUI_LIB -DQT_CORE_LIB
-DQT_TESTCASE_BUILDDIR=\"/home/travis/build/agt-the-walker/libkashogi-old/tests\"
-I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-clang -I. -I../src
-I/usr/include/qt5 -I/usr/include/qt5/QtTest -I/usr/include/qt5/QtGui
-I/usr/include/qt5/QtCore -I. -o piecetest.o piecetest.cpp
In file included from piecetest.cpp:2:
In file included from ./piecetest.h:1:
In file included from /usr/include/qt5/QtTest/QtTest:3:
In file included from /usr/include/qt5/QtTest/QtTestDepends:2:
In file included from /usr/include/qt5/QtCore/QtCore:39:
/usr/include/qt5/QtCore/qprocess.h:105:5: error: 'metaObject' overrides
a member
      function but is not marked 'override'
      [-Werror,-Winconsistent-missing-override]
    Q_OBJECT
    ^
[...]

Note that I couldn't reproduce this issue on my Arch system (with latest
updates).